### ISSUE TITLE
[BUG] Alert Pops up every time i go to /account/subscribed

### ISSUE THREAD

**Issue by slow-down** [Kamiikaze/Tampermonkey#1]
**Name of Script**
Advanced Streaming

**Version of Script**
3.3.10

**Describe the bug**
Every time i go to the /account/subscribed page i get an alert saying "saved 8 subscribed series.". 
Pretty annoying if i just want to watch a show i have to close the alert every single time

**To Reproduce**
1. Go to s.to/account/subscribed
2. See problem

**Enviroment (please complete the following information):**
 - Browser: Google Chrome
 - Addon: Tampermonkey

**Config of Script**
// # # # # # #
// CONFIG
// You can disable features by replacing the value true with false.
// # # # # # #

// Enables shorter Window Tab Title
// Example: S3E8 - Black Clover | AniWorld.to
const enableShortWindowTitle = true

// Hides the section of Season Suggestions below the video
const enableHideSeasonSuggestions = true

// Closing the dropdown menu when mouse leaves (fix the perma-open menu)
const enableCloseMenuOnHoverLeave = true

// Adding a Link below "Watch Trailer" to search for it on YT (Because sometimes there is a Homepage linked to the Anime)
const enableAddTrailerSearchLink = false

// Adding a small box at bottom left to search the Anime on sites like MyAnimeList, Crunchyroll & more
const enableAddAnimeSearchBox = false

// Enable/Disable search providers by changing the value either to true or false
// If you want to add your own provider let me know
const animeSearchProviderList = {
	'Crunchyroll': false,
	'aniSearch': false,
	'AnimePlanet': false,
	'MyAnimeList': true,
	'AmazonVideo': true,
}

// Adding a small box at bottom left to search the Series on sites like Amazon, Netflix & more
const enableAddSeriesSearchBox = false

// Enable/Disable search providers by changing the value either to true or false
// If you want to add your own provider let me know
const seriesSearchProviderList = {
	'AmazonVideo': true,
	'Netflix': true,
}

// Adding a small button at the right corner of the video frame to get to the next episode
const enableEpisodeNavButtons = true

// Allows filtering the Series Calendar by subscribed series
// To use this feature you need to go to https://s.to/account/subscribed and wait for the script to save the
// subscribed series. After that you can go to https://s.to/serienkalender and use the filter.
const enableFilterSeriesCalendar = true

// Adds a link to search series in the release calendar
const enableAddCalendarSearch = true

// Enable improved Search Box
// When pressing a key, search box will be automatically focused. Clicking the search box will select all input.
// By clicking outside the search box and pressing a key, the search box will be focused and cleared for new input.
const enableImprovedSearchBox = true

// # # # # # #
// Styling
// Some adjustments to layout.
// You can disable features by replacing the value true with false.
// # # # # # #

// Set the height of the video player. (in pixel)
// Set to 0 to disabled it. Default: 480
const reducePlayerHeight = 0

// Hides the text to show/edit the description of the episode below episode title
const hideDescriptionEdit = true

// Hides the language box above the video player
const hideLanguageBox = false

// Hides seen episodes (marked green) from the Episode-List (You can still see them in the season overview
const hideSeenEpisodes = false

// Use Scrollbar for Episode-List (good for seasons with a large amount of episodes)
const useScrollbarForEpisodeList = true

**Additional context**
Maybe it has something to do that i already subscribed to those shows before installing this script.
For now i just removed the alert line for my self.

**Comment by Kamiikaze** [comment]
Hey, yea this alert should be temporary and wanted to replace it with a better notify system.
I removed the alerts, should be better for now.

I'm still working on a better version as an chrome addon :)

**Comment by Kamiikaze** [comment]
Fixed with Commit https://github.com/Kamiikaze/Tampermonkey/commit/923a09ef8c09cd1e23dbbf9e3acf082da7a5061e
Replaced with Toast Notification in [v3.5.0](https://github.com/Kamiikaze/Tampermonkey/commit/7b9975648158a0bc8fd22826c2a149707c3022e0)
